version: "3"
services:
  server:
    build: .
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    container_name: server
    ports:
      - "8080:8080"
      - "40000:40000"